
["General Settings"]
	#Enable or disable configuration screen to edit in live different Eruannie's mod settings.
	Config_Screen = true
	#Determines which side the banner configuration appears on.
	Mirrored_Banner = true
	#Select the type of configuration button to display.
	#Allowed Values: BOOK, BANNER
	Button_Type = "BANNER"
	#Turn on/off animations within the config screen.
	Animations_Enabled = true
	#When to show in game update notices:
	#
	#NONE = Never.
	#SESSION = Once after the client starts.
	#WORLD_JOIN = Every time you join a world/server.
	#
	#Allowed Values: NONE, SESSION, WORLD_JOIN
	Update_Notices = "SESSION"
	#Pixel offsets applied to the config buttons relative to their default locations.
	#Positive X moves right, negative X moves left.
	#Positive Y moves down, negative Y moves up.
	#
	#Range: -400 ~ 400
	Banner_Offset_X = 0
	#Range: -400 ~ 400
	Banner_Offset_Y = 0
	#Range: -400 ~ 400
	Banner_Pause_Offset_X = 0
	#Range: -400 ~ 400
	Banner_Pause_Offset_Y = 0
	#Range: -400 ~ 400
	Book_Offset_X = 0
	#Range: -400 ~ 400
	Book_Offset_Y = 0

["Example Config Settings"]

	["Example Config Settings"."Basic Values"]
		#Stores a true or false value.
		Example_Boolean = true
		#Stores String, Integer, Long, Float and Double values.
		Example_String_Value = "exampole"
		#Stores one choice from a fixed set. Left click selects the next value. Right click selects the previous value.
		#Allowed Values: LOW, MEDIUM, HIGH
		Example_Enum = "MEDIUM"

	["Example Config Settings"."Special Editors"]
		#Stores an RGB or ARGB color value.
		Example_Color = "00FFFF"
		#Stores a list of registry names.
		Example_List = ["minecraft:grass_block", "minecraft:dirt", "minecraft:rooted_dirt"]

