#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 05 14:42:42 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=27
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=false
