#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 06 09:55:26 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=27
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=false
