#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,115", "CREATURE,22", "AMBIENT,20", "AXOLOTLS,8", "UNDERGROUND_WATER_CREATURE,10", "WATER_CREATURE,10", "WATER_AMBIENT,26"]

